### ISSUE TITLE
previous commands aren't cleared after hitting enter

### ISSUE THREAD

**Issue by NullVoxPopuli** [etkirsch/gmusic#13]

**Comment by etkirsch** [comment]
Can you elaborate? When does this happen?

**Comment by NullVoxPopuli** [comment]
to duplicate:

> be listening to music
> press:
i
pause
<enter>
> playback pauses but the `> pause` remains
> get tired of silence after some time
> press:
i
play
<enter>
> program crashes. 
> :-\

**Comment by etkirsch** [comment]
stack trace? I think I know what's wrong but I want to make sure

**Comment by etkirsch** [comment]
Should be fixed in most recent commit. Let me know if so

**Comment by NullVoxPopuli** [comment]
yup, fixed.
