### ISSUE TITLE
Now Playing pane doesn't update upon song change

### ISSUE THREAD

**Issue by NullVoxPopuli** [etkirsch/gmusic#21]
but if you pause, it updates

**Comment by etkirsch** [comment]
Are you on most recent commit? This seems to be a duplicate of issue #16.

This was addressed in d7a996d. Let me know if you're on the wrong commit

**Comment by NullVoxPopuli** [comment]
yup, my code was branched of slightly older master

**Comment by etkirsch** [comment]
Gracias
