### ISSUE TITLE
Next/Prev page doesn't do anything on the radios screen

### ISSUE THREAD

**Issue by NullVoxPopuli** [etkirsch/gmusic#24]
I can only see 64 radios, and no more.

**Comment by NullVoxPopuli** [comment]
left and right arrow keys work, so I guess the icons just need changing from [] to <- -> or ←, →

ref: http://www.w3schools.com/charsets/ref_utf_arrows.asp

**Comment by etkirsch** [comment]
Fixed in `exterminator` branch. I'll let you know when to verify
