### ISSUE TITLE
Radio sort order is backwards (imo)

### ISSUE THREAD

**Issue by NullVoxPopuli** [etkirsch/gmusic#28]
it's currently oldest first

I think it should be newest first

**Comment by etkirsch** [comment]
Fixed in `exterminator`

**Comment by etkirsch** [comment]
This is an interesting situation. I don't think it updates when it was most recently played, but I CAN index on creation date. I'll likely have to play around with this for a bit. But at the very least it's sorted by newest station (as in the OP)

**Comment by NullVoxPopuli** [comment]
well.. it's at least a little bit better.

**Comment by etkirsch** [comment]
A little bit

**Comment by etkirsch** [comment]
Don't close this one; I'm putting it under Update 1.1

**Comment by etkirsch** [comment]
This is fixed!
