### ISSUE TITLE
There should be a discoverable way to exit

### ISSUE THREAD

**Issue by NullVoxPopuli** [etkirsch/gmusic#42]
For non-cli-native users (or at least the unfamiliar with gmusic), exiting is non-trivial

**Comment by etkirsch** [comment]
Well, there is one. The CLI is the heart of gmusic, especially since all the menus do is just indirectly run the CLI. When the new CLI prompt is added, it will be more intuitive to use.

**Comment by NullVoxPopuli** [comment]
How does the user know that cli will contain exit?

core functionality should be easily available, rather than hidden

**Comment by etkirsch** [comment]
I just said that it's coming with the new CLI Prompt :P
