### ISSUE TITLE
When running inside an UbuntuVM, the audio clips at higher volumes

### ISSUE THREAD

**Issue by NullVoxPopuli** [etkirsch/gmusic#47]
Unsure if this is specific to the VM, the audio setup on the VM, or what....
Will try on a native ubuntu machine later.

**Comment by NullVoxPopuli** [comment]
Might be a virtualbox issue - might be virtualbox sound card/driver related

**Comment by NullVoxPopuli** [comment]
this is totally a virtualbox issue

**Comment by etkirsch** [comment]
:tada:
