### ISSUE TITLE
DJ Web Service

### ISSUE THREAD

**Issue by etkirsch** [etkirsch/gmusic#54]
P2P won't work for most people, so we need a way to do some sort of DJ service. This will be similar to Digitally Imported.

@NullVoxPopuli, let's see if it takes only 20 minutes!

**Comment by NullVoxPopuli** [comment]
:+1:

**Comment by NullVoxPopuli** [comment]
Over at https://github.com/NullVoxPopuli/gmusic-sync-service

**Comment by etkirsch** [comment]
:+1:
