### ISSUE TITLE
How much buffering does this use?

### ISSUE THREAD

**Issue by NullVoxPopuli** [etkirsch/gmusic#7]
Lets say I lose connection to the internet briefly,
 - how long will the music keep playing?
 - is there an option to increase the buffer size so that, if I *have* to be offline for, maybe 10 minutes, the queue will continue

**Comment by etkirsch** [comment]
Looking into this... Here's a starting point for myself later https://lazka.github.io/pgi-docs/Gst-1.0/structs/Buffer.html

**Comment by etkirsch** [comment]
Functions exactly the same as Google Music Web App -- Loads an entire song and no more
